In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [19]:
dataset = pd.read_csv('./dataset/Social_Network_Ads.csv')

In [20]:
dataset.head(15)

Age  EstimatedSalary  Purchased
0    19            19000          0
1    35            20000          0
2    26            43000          0
3    27            57000          0
4    19            76000          0
5    27            58000          0
6    27            84000          0
7    32           150000          1
8    25            33000          0
9    35            65000          0
10   26            80000          0
11   26            52000          0
12   20            86000          0
13   32            18000          0
14   18            82000          0

In [21]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [22]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [23]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size= 0.2, random_state=0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
model = keras.Sequential()

In [27]:
model.add(layers.Dense(units=2, activation='relu'))
model.add(layers.Dense(units=2, activation='relu'))
model.add(layers.Dense(units=1, activation='sigmoid'))

In [28]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [29]:
model.fit(X_train, Y_train, epochs=100, batch_size=32)

Epoch 1/100
10/10 [==============================] - 0s 4ms/step - loss: 0.7010 - accuracy: 0.3562
Epoch 2/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6969 - accuracy: 0.4156
Epoch 3/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6931 - accuracy: 0.5063
Epoch 4/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6896 - accuracy: 0.6094
Epoch 5/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6859 - accuracy: 0.6219
Epoch 6/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6830 - accuracy: 0.6219
Epoch 7/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6799 - accuracy: 0.6219
Epoch 8/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6768 - accuracy: 0.6219
Epoch 9/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6737 - accuracy: 0.6219
Epoch 10/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6705 - accuracy: 0.6219
Epoch 11/

10/10 [==============================] - 0s 2ms/step - loss: 0.4042 - accuracy: 0.7906
Epoch 84/100
10/10 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.7937
Epoch 85/100
10/10 [==============================] - 0s 3ms/step - loss: 0.4004 - accuracy: 0.7937
Epoch 86/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3986 - accuracy: 0.7937
Epoch 87/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3969 - accuracy: 0.7937
Epoch 88/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3952 - accuracy: 0.7937
Epoch 89/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3936 - accuracy: 0.7937
Epoch 90/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.7969
Epoch 91/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3903 - accuracy: 0.7969
Epoch 92/100
10/10 [==============================] - 0s 2ms/step - loss: 0.3886 - accuracy: 0.7969
Epoch 93/100


In [30]:
print(model.predict(sc.transform([[25,5000]])) > 0.5)

1/1 [==============================] - 0s 65ms/step
[[False]]


In [31]:
y_pred = model.predict(X_test)

3/3 [==============================] - 0s 2ms/step


In [32]:
y_pred = (y_pred > 0.5)

In [33]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]]


In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[54  4]
 [ 3 19]]


0.9125